# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: sort uniq project.list
      run: |
        sort project.list -k2,2 | sort -u -o project.list
    - name: Gen README
      run: |
        python .github/gen.py
    - name: Commit files
      run: |
        git config --local user.name  ${{ github.actor }}
        git add README.md
        git commit -m "Generate by actions"
        git push
